### ISSUE TITLE
Interval versions of functions that return NaN

### ISSUE THREAD

**Issue by dmcclean** [ekmett/intervals#21]
Applying the same `conservative :: (a -> a) -> (Interval a -> Interval a) -> Property` property that I wrote to test the trig functions, I found some other interesting counterexamples that raise a design question.

I expected that the essence of the interval version of, say, `sin`, is that it's a conservative approximation of the scalar version. So if you pick a value in the interval `x` and evaluate `sin` there, the result will be in the interval `sin x`. (This isn't the entirety of what we want, since we want the "best" such approximation, but it's a start.)

Our current definitions of some functions fail this test for values that are outside the domain. `log (-2)` is `NaN`, and `log (-3 ... -1)` is `NaN ... -Infinity` (which seems like a strange beast in its own right...), but `NaN` is not an element of `NaN ... -Infinity` because of the way the `Ord Double` instance works.

For the interval type where `Empty` is an option, it seems like a good one and the current definitions take it. If `NaN` could somehow be an element of `Empty` that would be even better, but I'm not sure if there is a parametric way to do that. So all we would do would be to relax the definition of conservativeness that we have in our heads.

For the non empty interval type it is a bit thornier. Returning `whole` instead of `Empty` seems like an option. It's conservative, just not very. ;) Might be more user friendly than an exception, but then again maybe an exception is the right thing to do. Perhaps making `NaN` an element of the strange interval we return now would be OK, but with the same parametricity thorn. I'm not sure what other `Floating` instances might be lurking out there that don't have `NaN`ish things or where those definitions would leave them. Rounded? Fixed?

**Comment by bergey** [comment]
Fixed by https://github.com/ekmett/intervals/pull/36
