### ISSUE TITLE
recip is not conservative

### ISSUE THREAD

**Issue by dmcclean** [ekmett/intervals#23]
```
Prelude Numeric.Interval> let x = -4.953054227393486 ... 1.7338039918518358
Prelude Numeric.Interval> let y = -1.5469134120041255
Prelude Numeric.Interval> recip x
-0.2018956292603006 ... 0.576766465355708
Prelude Numeric.Interval> recip y
-0.6464485938514399
```

I'm not exactly sure where the problem arises. The definition looks OK to me at first glance, `recip (I a b)   = on min recip a b ... on max recip a b`, but I often have difficulty understanding `on`.

**Comment by bergey** [comment]
Fixed by https://github.com/ekmett/intervals/pull/36
