### ISSUE TITLE
Semigroup / Monoid instance

### ISSUE THREAD

**Issue by phadej** [ekmett/intervals#39]
Does it make sense to have:

``` hs
instance Ord a => Semigroup (Interval a) where
  (<>) = hull

instance Ord => Monoid (Interval a) wherre
  mempty = empty
  mappend = (<>)
```

I could make a PR, if these instances are OK

**Comment by bergey** [comment]
Things to think about:
- We'd incur a `semigroups` dependency
- `intersection` is also a semigroup / monoid

It looks like the [the revdeps](http://packdeps.haskellers.com/reverse/intervals) already depend on `semigroups`.  I'm leaning towards a newtype for one or both instances.

**Comment by phadej** [comment]
`intersection` is a partial function for non-empty variant, thus I'd prefer `Semigroup` for it.
The newtype for normal variant could be useful indeed: `newtype Intersection a = Intersection (Interval a)` with `mempty = Intersection whole` ?

**Comment by Icelandjack** [comment]
@bergey
`Data.Semigroup` is now in base if that matters,

I was hoping to use this for a similar purpose to `data Interval = Between Time Time` from [*Constructing Applicative Functors*](http://www.staff.city.ac.uk/~ross/papers/Constructors.pdf).
